//
//  CompressionServiceTests.swift
//  VideoCompressorTests
//
//  Integration coverage for the Phase 3 AVAssetWriter pipeline. Uses a
//  fixture at /tmp/sample_test_video.mp4 (a 720p 8 s ~5 Mbps H.264 + AAC
//  clip generated by ffmpeg). When the fixture is missing the tests
//  skip with `XCTSkip` rather than fail — running on CI without the
//  fixture should not break the build.
//

import XCTest
import AVFoundation
@testable import VideoCompressor_iOS

final class CompressionServiceTests: XCTestCase {

    /// Path to the fixture video. Generated outside the harness via:
    ///   ffmpeg -y -f lavfi -i "color=c=blue:s=1280x720:d=8:r=30,noise=alls=80:allf=t" \
    ///          -f lavfi -i sine=frequency=1000:duration=8 \
    ///          -c:v libx264 -b:v 5000k ... /tmp/sample_test_video.mp4
    private let fixtureURL = URL(fileURLWithPath: "/tmp/sample_test_video.mp4")

    private func requireFixture() throws -> URL {
        guard FileManager.default.fileExists(atPath: fixtureURL.path) else {
            throw XCTSkip("Fixture /tmp/sample_test_video.mp4 not available; skipping integration test.")
        }
        return fixtureURL
    }

    private func sourceBytes(_ url: URL) -> Int64 {
        ((try? FileManager.default.attributesOfItem(atPath: url.path)[.size]) as? NSNumber)?.int64Value ?? 0
    }

    // MARK: - Smart-cap acceptance: small preset shrinks the source

    func testSmallPresetProducesStrictlySmallerOutput() async throws {
        let input = try requireFixture()
        let srcSize = sourceBytes(input)
        XCTAssertGreaterThan(srcSize, 0, "Fixture must have non-zero size.")

        let service = CompressionService()
        let outURL = try await service.compress(
            input: input,
            settings: .small,
            onProgress: { _ in }
        )
        defer { try? FileManager.default.removeItem(at: outURL) }

        let outSize = sourceBytes(outURL)
        XCTAssertGreaterThan(outSize, 0, "Output should exist and be non-empty.")
        XCTAssertLessThan(
            outSize, srcSize,
            "Small preset must produce a file smaller than source. src=\(srcSize) out=\(outSize)"
        )
    }

    // MARK: - Max preset round-trips at roughly source bitrate

    func testMaxPresetPreservesSourceBitrate() async throws {
        let input = try requireFixture()
        let srcSize = sourceBytes(input)

        let service = CompressionService()
        let outURL = try await service.compress(
            input: input,
            settings: .max,
            onProgress: { _ in }
        )
        defer { try? FileManager.default.removeItem(at: outURL) }

        let outSize = sourceBytes(outURL)
        XCTAssertGreaterThan(outSize, 0)
        // Max preset re-encodes at source bitrate, but switches H.264 → HEVC,
        // which is ~30-50% more efficient at equal quality. So the output is
        // expected to be smaller. We just assert it's reasonable: within 2×
        // either direction of source size to catch absurd outliers.
        XCTAssertLessThan(outSize, srcSize * 2, "Max output should not balloon vs source.")
        XCTAssertGreaterThan(outSize, srcSize / 4, "Max output should not collapse.")
    }

    // MARK: - Cancellation

    func testCancellationStopsEncodeAndCleansUp() async throws {
        let input = try requireFixture()
        let service = CompressionService()

        // Predict the output URL the service will write to so we can verify
        // cleanup after cancellation.
        let predicted = CompressionService.outputURL(forInput: input, settings: .small)
        try? FileManager.default.removeItem(at: predicted)

        let task = Task {
            try await service.compress(
                input: input,
                settings: .small,
                onProgress: { _ in }
            )
        }

        // Give the encoder a beat to start, then cancel.
        try? await Task.sleep(nanoseconds: 200_000_000)
        task.cancel()

        var threwCancelled = false
        do {
            _ = try await task.value
        } catch CompressionError.cancelled {
            threwCancelled = true
        } catch is CancellationError {
            threwCancelled = true
        } catch {
            // Other errors are allowed — what matters is that the task
            // halted promptly rather than running to completion.
            threwCancelled = true
        }
        XCTAssertTrue(threwCancelled, "Cancelled encode should throw.")

        // Output must not be left behind at the predicted URL.
        XCTAssertFalse(
            FileManager.default.fileExists(atPath: predicted.path),
            "Cancelled encode must not leave an output file at \(predicted.path)."
        )
    }

    // MARK: - Cluster 0 writer safety settings

    func testSDRColorPropertiesShape() {
        let props = CompressionService.sdrColorProperties()
        XCTAssertEqual(
            props[AVVideoColorPrimariesKey] as? String,
            AVVideoColorPrimaries_ITU_R_709_2
        )
        XCTAssertEqual(
            props[AVVideoTransferFunctionKey] as? String,
            AVVideoTransferFunction_ITU_R_709_2
        )
        XCTAssertEqual(
            props[AVVideoYCbCrMatrixKey] as? String,
            AVVideoYCbCrMatrix_ITU_R_709_2
        )
    }

    func testFrameRateClampedToMax120() {
        XCTAssertEqual(CompressionService.clamp(frameRate: 30), 30)
        XCTAssertEqual(CompressionService.clamp(frameRate: 60), 60)
        XCTAssertEqual(CompressionService.clamp(frameRate: 120), 120)
        XCTAssertEqual(
            CompressionService.clamp(frameRate: 240), 120,
            "240 fps slow-mo must clamp to 120."
        )
        XCTAssertEqual(
            CompressionService.clamp(frameRate: 0), 30,
            "Zero/missing nominalFrameRate must default to 30."
        )
    }

    func testGopClampedToMax60() {
        XCTAssertEqual(CompressionService.clamp(gop: 60), 60)
        XCTAssertEqual(
            CompressionService.clamp(gop: 240), 60,
            "Slow-mo GOP must clamp to 60."
        )
        XCTAssertEqual(
            CompressionService.clamp(gop: 1), 2,
            "GOP must be at least 2."
        )
    }
}
