schemaVersion: 1
enabledWorkflows:
  - coverage
  - debugging
  - device
  - logging
  - project-discovery
  - project-scaffolding
  - simulator
  - simulator-management
  - ui-automation
  - utilities
incrementalBuildsEnabled: false
sessionDefaults:
  configuration: Debug
  simulatorName: iPhone 16 Pro
  useLatestOS: true
  platform: iOS
  projectPath: VideoCompressor/VideoCompressor_iOS.xcodeproj
  scheme: VideoCompressor_iOS
  simulatorId: 996226E2-F957-4730-93D5-4F10BFD916C3
debug: false
sentryDisabled: true
